import pytest
import torch
from pathlib import Path

from data.gnn_dataset import E3GNNDataset
from data.snapshot import Snapshot
from core.block_irrep_mapper import BlockIrrepMapper
from data.graph_features import compute_graph_features
from net.common import Config
from net.e3gnn import E3GNN


@pytest.fixture(scope="module")
def h2o_data():
    cfg = Config(cutoff_matrix=15.0)
    snap = Snapshot.from_openmx(
        matrix_path=Path("data/small/H2O/original/H2O.matrix"),
        info_path=Path("data/small/H2O/original/H2O.info.out"),
        cfg=cfg,
    )
    orb_cfg = snap.hamiltonian.orbital_cfg
    mapper = BlockIrrepMapper(
        orb_cfg,
        diagonal=False,
        device="cpu",
        dtype=cfg.dtype,
    )

    return snap, cfg, mapper


@pytest.mark.integration
def test_precomputed_vs_onthefly_features(h2o_data):
    """
    Directly tests that edge features from a precomputing dataset are identical
    to features generated by the standalone compute_graph_features function.
    """
    snap, cfg, mapper = h2o_data

    import os

    # print the current working directory for debugging
    print("Current working directory:", os.getcwd())
    dataset_precompute = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg,
    )

    # Get the processed sample. x_precompute contains the features we want to verify.
    x_precompute, _ = dataset_precompute[0]

    # --- 2. Generate features directly using the on-the-fly path ---
    # This simulates what E3GNN.forward would do if precomputation was False.
    (
        edge_index_direct,
        edge_shift_direct,
        edge_type_idx_direct,
        edge_length_emb_direct,
        edge_sh_direct,
        index_gnn_cutoff_direct,
        num_self_edges_direct,
    ) = compute_graph_features(
        positions=snap.positions,
        box=snap.box,
        atoms=snap.density.atoms,
        cfg=cfg,  # Use the same config for a fair comparison
        sh_irreps=dataset_precompute.sh_irreps,
        edge_type2idx=mapper.edge_type2idx,
    )

    # --- 3. Assert that the outputs are identical ---
    # For integer tensors, we can check for exact equality.
    assert torch.equal(
        x_precompute["edge_index"], edge_index_direct
    ), "edge_index mismatch"
    assert torch.equal(
        x_precompute["edge_shift"], edge_shift_direct
    ), "edge_shift mismatch"
    assert torch.equal(
        x_precompute["edge_type_idx"], edge_type_idx_direct
    ), "edge_type_idx mismatch"

    # For floating-point tensors, use allclose to account for minor precision differences.
    assert torch.allclose(
        x_precompute["edge_length_emb"], edge_length_emb_direct
    ), "edge_length_emb mismatch"
    assert torch.allclose(x_precompute["edge_sh"], edge_sh_direct), "edge_sh mismatch"

    # For scalar integers, use direct comparison.
    assert (
        x_precompute["index_gnn_cutoff"] == index_gnn_cutoff_direct
    ), "index_gnn_cutoff mismatch"
    assert (
        x_precompute["num_self_edges"] == num_self_edges_direct
    ), "num_self_edges mismatch"


@pytest.mark.skip(reason="On-the-fly features temporarily not supported")
@pytest.mark.integration
def test_e3gnn_end_to_end_consistency(h2o_data):
    """
    Tests that the full E3GNN model produces identical final outputs
    whether features are precomputed or computed on-the-fly.
    """
    snap, cfg, mapper = h2o_data

    # --- 1. Setup and run for PRECOMPUTED features ---
    cfg_precompute = Config(
        l_max_gnn=1,
        n_radial=16,
        precompute_edge_features=True,  # Precompute mode
        safety_checks=True,
    )
    dataset_precompute = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg_precompute,
    )
    x_precompute, _ = dataset_precompute[0]

    torch.manual_seed(42)  # Reset seed right before creating the first model
    model_precompute = E3GNN(mapper, cfg_precompute)
    preds_precompute = model_precompute(x_precompute)

    # --- 2. Setup and run for ON-THE-FLY features ---
    cfg_onthefly = Config(
        l_max_gnn=1,
        n_radial=16,
        precompute_edge_features=False,  # On-the-fly mode
        safety_checks=True,
    )
    dataset_onthefly = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg_onthefly,
    )
    x_onthefly, _ = dataset_onthefly[0]

    torch.manual_seed(42)  # Reset seed AGAIN to the same state
    model_onthefly = E3GNN(mapper, cfg_onthefly)
    preds_onthefly = model_onthefly(x_onthefly)

    # --- 3. Assert that the final predictions are identical ---
    # Compare predictions for Hamiltonian, Overlap, and Density
    for matrix_name in ["hamiltonian", "overlap", "density"]:
        pred_precompute_vectors = preds_precompute[matrix_name].pair_vectors
        pred_onthefly_vectors = preds_onthefly[matrix_name].pair_vectors

        # Check that the same element-pair keys were predicted
        assert set(pred_precompute_vectors.keys()) == set(pred_onthefly_vectors.keys())

        # Check that the irrep vectors for each key are numerically close
        for key in pred_precompute_vectors.keys():
            assert torch.allclose(
                pred_precompute_vectors[key],
                pred_onthefly_vectors[key],
                atol=1e-6,  # Use a small tolerance for floating point comparisons
            ), f"Mismatch in final prediction for {matrix_name} matrix, key {key}"
