import pytest
import torch
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace

from data.gnn_dataset import E3GNNDataset
from data.snapshot import Snapshot
from data.factory import DatasetFactory
from core.block_irrep_mapper import BlockIrrepMapper
from data.graph_features import compute_graph_features
from net.common import Config
from net.e3gnn import E3GNN


@pytest.fixture(scope="module")
def h2o_data(small_angular_snapshot_e3nn):
    cfg = Config(
        cutoff_radius=5.0,
        l_max=1,
        hidden_base_dim=2,
        hidden_irreps="2x0e+2x0o+1x1e+1x1o",
        n_radial=4,
        radial_layers=[4],
        num_layers_gnn=1,
        neck_depth=1,
        internal_e3mlp_layers=1,
        head_e3mlp_layers=1,
        safety_checks=True,
    )
    snap = small_angular_snapshot_e3nn
    orb_cfg = snap.hamiltonian.orbital_cfg
    mapper = BlockIrrepMapper(
        orb_cfg,
        diagonal=False,
        device="cpu",
        dtype=cfg.dtype,
    )

    return snap, cfg, mapper


@pytest.fixture
def synthetic_dataset_loader(monkeypatch, small_angular_snapshot_e3nn):
    monkeypatch.setattr(
        Snapshot,
        "from_openmx",
        lambda *args, **kwargs: small_angular_snapshot_e3nn,
    )
    monkeypatch.setattr(
        DatasetFactory,
        "_load_info",
        lambda self, *paths: SimpleNamespace(orbital_set={"H": "1s1p"}),
    )


@pytest.mark.integration
def test_precomputed_vs_onthefly_features(h2o_data, synthetic_dataset_loader):
    """
    Directly tests that edge features from a precomputing dataset are identical
    to features generated by the standalone compute_graph_features function.
    """
    snap, cfg, mapper = h2o_data

    dataset_precompute = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg,
    )

    # Get the processed sample. x_precompute contains the features we want to verify.
    x_precompute, _ = dataset_precompute[0]

    # --- 2. Generate features directly using the on-the-fly path ---
    # This simulates what E3GNN.forward would do if precomputation was False.
    (
        edge_index_direct,
        edge_shift_direct,
        edge_type_idx_direct,
        edge_length_emb_direct,
        edge_sh_direct,
        num_self_edges_direct,
        edge_lengths_direct,
    ) = compute_graph_features(
        positions=snap.positions,
        box=snap.box,
        atoms=snap.density.atoms,
        cfg=cfg,  # Use the same config for a fair comparison
        sh_irreps=dataset_precompute.sh_irreps,
        edge_type2idx=mapper.edge_type2idx,
    )

    # --- 3. Assert that the outputs are identical ---
    # For integer tensors, we can check for exact equality.
    assert torch.equal(
        x_precompute["edge_index"], edge_index_direct
    ), "edge_index mismatch"
    assert torch.equal(
        x_precompute["edge_shift"], edge_shift_direct
    ), "edge_shift mismatch"
    assert torch.equal(
        x_precompute["edge_type_idx"], edge_type_idx_direct
    ), "edge_type_idx mismatch"

    # For floating-point tensors, use allclose to account for minor precision differences.
    assert torch.allclose(
        x_precompute["edge_length_emb"], edge_length_emb_direct
    ), "edge_length_emb mismatch"
    assert torch.allclose(x_precompute["edge_sh"], edge_sh_direct), "edge_sh mismatch"
    assert torch.allclose(
        x_precompute["edge_length"], edge_lengths_direct
    ), "edge_length mismatch"

    # For scalar integers, use direct comparison.
    assert (
        x_precompute["num_self_edges"] == num_self_edges_direct
    ), "num_self_edges mismatch"


@pytest.mark.integration
def test_e3gnn_end_to_end_consistency(h2o_data, synthetic_dataset_loader):
    """
    Tests that the full E3GNN model produces identical final outputs
    whether features are precomputed or computed on-the-fly.
    """
    snap, cfg, mapper = h2o_data

    # --- 1. Setup and run for PRECOMPUTED features ---
    cfg_precompute = replace(cfg, precompute_edge_features=True)
    dataset_precompute = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg_precompute,
    )
    x_precompute, _ = dataset_precompute[0]

    torch.manual_seed(42)  # Reset seed right before creating the first model
    model_precompute = E3GNN(mapper, cfg_precompute)
    preds_precompute = model_precompute(x_precompute)

    # --- 2. Setup and run for ON-THE-FLY features ---
    cfg_onthefly = replace(cfg, precompute_edge_features=False)
    dataset_onthefly = E3GNNDataset(
        snapshot_paths=[
            (
                Path("data/small/H2O/original/H2O.matrix"),
                Path("data/small/H2O/original/H2O.info.out"),
            )
        ],
        mapper=mapper,
        cfg=cfg_onthefly,
    )
    x_onthefly, _ = dataset_onthefly[0]

    torch.manual_seed(42)  # Reset seed AGAIN to the same state
    model_onthefly = E3GNN(mapper, cfg_onthefly)
    preds_onthefly = model_onthefly(x_onthefly)

    # --- 3. Assert that the final predictions are identical ---
    for matrix_name in cfg.matrix_targets:
        pred_precompute_vectors = preds_precompute[matrix_name].pair_vectors
        pred_onthefly_vectors = preds_onthefly[matrix_name].pair_vectors

        # Check that the same element-pair keys were predicted
        assert set(pred_precompute_vectors.keys()) == set(pred_onthefly_vectors.keys())

        # Check that the irrep vectors for each key are numerically close
        for key in pred_precompute_vectors.keys():
            assert torch.allclose(
                pred_precompute_vectors[key],
                pred_onthefly_vectors[key],
                atol=1e-6,  # Use a small tolerance for floating point comparisons
            ), f"Mismatch in final prediction for {matrix_name} matrix, key {key}"
