# Default E3GNN model hyper-parameters
l_max:                3
hidden_base_dim:      64
num_layers_gnn:       2
num_layers_matrix:    1
use_edge_updates:     true
use_self_update:      true
nonlin_kind:          "gate"
activation_scalar:    "silu"
batch_norm:           false
norm_kind:            "component"
dropout:              0.0
residual_connections: true
n_radial:             64
radial_layers:        [128]
share_radial:         true
head_depth:           1
head_hidden_mul:      1.0
hidden_mul_clip:      4.0
energy_loss_coef:     1e-5
electron_loss_coef:   1e-5
