source mandala-venv/bin/activate
python studies/minimal_silicon_study/train_silicon_minimal.py \
  --data-path /bigdata/casus/wdm/hamiltonian_learning/data/silicon_very_big/dataset_A \
  --val-temp 2700 \
  --train-temps 2700 \
  --n-snapshots-per-temp 100 \
  --val-n-snapshots 10 \
  --log-interval 20 \
  --adaptive-log-interval \
  --benchmark \
  --log-data \
  --log-model \
  --log-per-irrep-metrics \
  --log-per-irrep-images \
  --generate-video \
  --lr 0.01 \
  --num-epochs 1000 \
  --l-max 4 \
  --hidden-irreps 32x0e+32x1e+32x1o+16x2e+16x2o+16x3e+16x3o+8x4e \
  --separate-shifted-self \
  --num-layers 2 \
  --train-on-irrep-parts \
  --orbital-selection 1s1p \
  --run-name bigger_train_1s1p
