"""
Minimal E(3)-Equivariant Network Study: Overfit Single Water Structure
=======================================================================

This study implements the SIMPLEST possible E(3)-equivariant GNN from scratch
to overfit on a single H2O snapshot. Everything is done explicitly without
importing high-level classes like E3GNN or E3GNNDataset.

Goal: Achieve highest possible accuracy through aggressive overfitting.

Architecture:
- Simple node encoder: element embedding → scalars
- Simple edge encoder: distance + spherical harmonics
- 1-2 message passing layers with basic tensor products
- Simple head: edge features → matrix blocks via BlockIrrepMapper

Verbose logging at every step for educational purposes.
"""

import sys
import os
from pathlib import Path
import argparse
import torch
import torch.nn.functional as F
from torch.optim import Adam

from net.common import build_hidden_irreps

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from e3nn.o3 import Irreps, spherical_harmonics
from e3nn.math import soft_one_hot_linspace
from ase import Atoms
from ase.neighborlist import neighbor_list

# Import only low-level data structures
from data.snapshot import Snapshot
from core.block_irrep_mapper import BlockIrrepMapper

# WandB for logging
import wandb

# Import network classes and utilities from common module
from common import (
    MinimalNetwork,
    compute_detailed_metrics,
)


if __name__ == "__main__":
    # =============================================================================
    # PARSE ARGUMENTS
    # =============================================================================
    parser = argparse.ArgumentParser(
        description="Minimal E(3)-Equivariant Network: Overfit Single Water Structure"
    )
    parser.add_argument(
        "--data-path",
        type=str,
        default=str(project_root / "data/small/H2O/original/H2O.matrix"),
        help="Path to the matrix file",
    )
    parser.add_argument(
        "--info-path",
        type=str,
        default=str(project_root / "data/small/H2O/original/H2O.info.out"),
        help="Path to the info file",
    )
    parser.add_argument(
        "--hidden-dim",
        type=int,
        default=32,
        help="Hidden dimension for features (used if --hidden-irreps not provided)",
    )
    parser.add_argument(
        "--l-max",
        type=int,
        default=2,
        help="Maximum angular momentum (used if --hidden-irreps not provided)",
    )
    parser.add_argument(
        "--hidden-irreps",
        type=str,
        default=None,
        help="Hidden irreps string (e.g., '32x0e+32x1o+32x2e'). If not provided, will be constructed using build_hidden_irreps with --hidden-dim and --l-max",
    )
    parser.add_argument(
        "--num-layers",
        type=int,
        default=2,
        help="Number of message passing layers",
    )
    parser.add_argument(
        "--cutoff-radius",
        type=float,
        default=8.0,
        help="Cutoff radius in Angstroms",
    )
    parser.add_argument(
        "--n-radial",
        type=int,
        default=16,
        help="Number of radial basis functions",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate",
    )
    parser.add_argument(
        "--num-epochs",
        type=int,
        default=1000,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--log-interval",
        type=int,
        default=200,
        help="Interval for logging",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device to use (cuda or cpu)",
    )
    parser.add_argument(
        "--checkpoint-dir",
        type=str,
        default=str(project_root / "studies/minimal_overfit_study/checkpoints"),
        help="Directory to save checkpoints",
    )
    parser.add_argument(
        "--run-name",
        type=str,
        default=None,
        help="WandB run name (default: auto-generated by WandB)",
    )

    args = parser.parse_args()

    # =============================================================================
    # CONFIGURATION
    # =============================================================================
    print("=" * 80)
    print("MINIMAL WATER OVERFIT STUDY - EXPLICIT IMPLEMENTATION")
    print("=" * 80)
    print("\n[CONFIG] Setting up hyperparameters...")

    CONFIG = {
        # Data
        "data_path": Path(args.data_path),
        "info_path": Path(args.info_path),
        # Network architecture
        "hidden_dim": args.hidden_dim,
        "l_max": args.l_max,
        "hidden_irreps": args.hidden_irreps,  # Can be None
        "num_layers": args.num_layers,
        "cutoff_radius": args.cutoff_radius,
        "n_radial": args.n_radial,
        # Training
        "lr": args.lr,
        "num_epochs": args.num_epochs,
        "log_interval": args.log_interval,
        # Device
        "device": args.device,
        # Target
        "train_target": "matrix",
        # Checkpointing
        "checkpoint_dir": Path(args.checkpoint_dir),
    }

    # Initialize WandB
    wandb_kwargs = {
        "project": "mandala-minimal-overfit-study",
        "config": CONFIG,
    }
    if args.run_name is not None:
        wandb_kwargs["name"] = args.run_name
    wandb.init(**wandb_kwargs)

    # Create run-specific checkpoint directory
    run_name = wandb.run.name
    run_checkpoint_dir = CONFIG["checkpoint_dir"] / run_name
    run_checkpoint_dir.mkdir(parents=True, exist_ok=True)
    print(f"  Run-specific checkpoint directory: {run_checkpoint_dir}")

    print(f"  Device: {CONFIG['device']}")
    print(f"  Hidden dim: {CONFIG['hidden_dim']}")
    print(f"  L_max: {CONFIG['l_max']}")
    print(f"  Num layers: {CONFIG['num_layers']}")
    print(f"  Cutoff radius: {CONFIG['cutoff_radius']} Å")
    print(f"  Learning rate: {CONFIG['lr']}")
    print(f"  Epochs: {CONFIG['num_epochs']}")

    device = torch.device(CONFIG["device"])

    # Create checkpoint directory
    CONFIG["checkpoint_dir"].mkdir(parents=True, exist_ok=True)
    print(f"  Checkpoint directory: {CONFIG['checkpoint_dir']}")

    # =============================================================================
    # LOAD DATA
    # =============================================================================
    print("\n[DATA] Loading single water snapshot...")

    # Load snapshot using Snapshot.from_openmx
    print(f"  Matrix file: {CONFIG['data_path']}")
    print(f"  Info file: {CONFIG['info_path']}")

    snapshot = Snapshot.from_openmx(
        matrix_path=CONFIG["data_path"],
        info_path=CONFIG["info_path"],
        convention="e3nn",  # Automatically converts to e3nn basis
        symmetrize_density=True,
        cutoff_radius=None,  # No filtering, we'll use all edges
        dtype=torch.float32,
    )

    print(f"\n  Snapshot loaded:")
    print(f"    Elements: {snapshot.hamiltonian.atoms}")
    print(f"    Num atoms: {len(snapshot.hamiltonian.atoms)}")
    print(f"    Positions shape: {snapshot.positions.shape}")
    print(f"    Box shape: {snapshot.box.shape if snapshot.box is not None else None}")
    print(f"    Basis: {snapshot.hamiltonian.basis}")

    print(f"\n  Matrices:")
    print(f"    Hamiltonian keys: {list(snapshot.hamiltonian.pair_blocks.keys())}")
    print(f"    Overlap keys: {list(snapshot.overlap.pair_blocks.keys())}")
    print(f"    Density keys: {list(snapshot.density.pair_blocks.keys())}")

    print(f"\n  Hamiltonian blocks:")
    for key, blocks in snapshot.hamiltonian.pair_blocks.items():
        print(
            f"    {key}: shape {blocks.shape}, edges {snapshot.hamiltonian.pair_edges[key].shape}"
        )

    # Extract components
    hamiltonian_e3nn = snapshot.hamiltonian.to(device)
    overlap_e3nn = snapshot.overlap.to(device)
    density_e3nn = snapshot.density.to(device)
    orbital_cfg = snapshot.hamiltonian.orbital_cfg
    positions = snapshot.positions.to(device)
    box = snapshot.box.to(device) if snapshot.box is not None else None
    atoms_list = list(snapshot.hamiltonian.atoms)

    print(f"\n  Orbital configuration:")
    for elem in orbital_cfg.elements():
        irreps = orbital_cfg.element_to_irreps[elem]
        print(f"    {elem}: {irreps} (dim={irreps.dim})")

    # Create BlockIrrepMapper
    print("\n[MAPPER] Creating BlockIrrepMapper...")
    mapper = BlockIrrepMapper(orbital_cfg, device=device, dtype=torch.float32)
    print(f"  Mapper edge types: {mapper.edge_types}")
    print(f"  Mapper edge_type2idx: {mapper.edge_type2idx}")

    # Store target as matrix blocks (train_target = "matrix")
    print("\n[TARGETS] Storing target as matrix blocks...")
    target_H_matrix = hamiltonian_e3nn

    print("  Target matrix blocks:")
    for key in target_H_matrix.pair_blocks.keys():
        block_shape = target_H_matrix.pair_blocks[key].shape
        edge_shape = target_H_matrix.pair_edges[key].shape
        pair_irreps = mapper.get_pair_irreps(key)
        print(
            f"    {key}: blocks {block_shape}, edges {edge_shape}, irreps {pair_irreps}"
        )

    # =============================================================================
    # BUILD GRAPH
    # =============================================================================
    print("\n[GRAPH] Constructing molecular graph...")

    num_atoms = len(atoms_list)

    print(f"  Atoms: {atoms_list}")
    print(f"  Positions (e3nn frame):\n{positions}")
    if box is not None:
        print(f"  Box (e3nn frame):\n{box}")

    # Create ASE atoms object for neighbor list
    ase_atoms = Atoms(
        symbols=atoms_list,
        positions=positions.cpu().numpy(),
        cell=box.cpu().numpy() if box is not None else None,
        pbc=box is not None,
    )

    # Find neighbors using ASE
    print(f"\n  Finding neighbors within {CONFIG['cutoff_radius']} Å...")
    src, dst, offsets = neighbor_list(
        "ijS", ase_atoms, CONFIG["cutoff_radius"], self_interaction=False
    )

    print(f"  Found {len(src)} off-diagonal edges")
    print(f"  Edge list (first 10):")
    for i in range(min(10, len(src))):
        print(f"    {src[i]} → {dst[i]} (offset: {offsets[i]})")

    # Add self-edges
    self_src = torch.arange(num_atoms, dtype=torch.long, device=device)
    self_dst = torch.arange(num_atoms, dtype=torch.long, device=device)
    self_offsets = torch.zeros((num_atoms, 3), dtype=torch.long, device=device)

    # Combine all edges
    all_src = torch.cat([self_src, torch.from_numpy(src).to(device)])
    all_dst = torch.cat([self_dst, torch.from_numpy(dst).to(device)])
    all_offsets = torch.cat([self_offsets, torch.from_numpy(offsets).to(device).long()])

    edge_index = torch.stack([all_src, all_dst], dim=0)  # (2, E)
    edge_shift = all_offsets.T  # (3, E)

    num_self_edges = num_atoms
    print(
        f"  Total edges: {edge_index.shape[1]} ({num_self_edges} self + {edge_index.shape[1] - num_self_edges} off-diagonal)"
    )

    # Compute edge vectors and distances
    print("\n  Computing edge displacements and distances...")
    if box is not None:
        shift_float = edge_shift.T.float()
        edge_vec = (
            positions[edge_index[1]] - positions[edge_index[0]] + shift_float @ box
        )
    else:
        edge_vec = positions[edge_index[1]] - positions[edge_index[0]]

    edge_dist = torch.linalg.norm(edge_vec, dim=1)

    print(
        f"  Edge distances (Å): min={edge_dist.min().item():.3f}, max={edge_dist.max().item():.3f}, mean={edge_dist.mean().item():.3f}"
    )
    print(f"  Self-edge distances: {edge_dist[:num_self_edges]}")

    # Compute spherical harmonics
    print(f"\n  Computing spherical harmonics (l_max={CONFIG['l_max']})...")
    sh_irreps = Irreps.spherical_harmonics(CONFIG["l_max"])
    print(f"  SH irreps: {sh_irreps}")

    # Normalize edge vectors (avoid division by zero for self-edges)
    edge_vec_norm = edge_vec.clone()
    non_zero_mask = edge_dist > 1e-6
    edge_vec_norm[non_zero_mask] = edge_vec[non_zero_mask] / edge_dist[
        non_zero_mask
    ].unsqueeze(-1)

    edge_sh = spherical_harmonics(sh_irreps, edge_vec_norm, normalize=False)
    print(f"  Edge SH shape: {edge_sh.shape}")

    # Radial basis functions
    print(f"\n  Computing radial embeddings ({CONFIG['n_radial']} basis functions)...")
    edge_length_emb = soft_one_hot_linspace(
        edge_dist,
        start=0.0,
        end=CONFIG["cutoff_radius"],
        number=CONFIG["n_radial"],
        basis="gaussian",
        cutoff=False,
    )
    edge_length_emb = edge_length_emb * CONFIG["n_radial"] ** 0.5  # Normalization
    print(f"  Edge length embedding shape: {edge_length_emb.shape}")

    # Edge type indices
    print("\n  Computing edge type indices...")
    element_to_idx = {elem: idx for idx, elem in enumerate(orbital_cfg.elements())}
    print(f"  Element to index: {element_to_idx}")

    node_type_idx = torch.tensor([element_to_idx[a] for a in atoms_list], device=device)
    src_type = node_type_idx[edge_index[0]]
    dst_type = node_type_idx[edge_index[1]]

    # Create edge type strings and map to indices
    edge_type_strs = [
        f"{atoms_list[edge_index[0, i].item()]}-{atoms_list[edge_index[1, i].item()]}"
        for i in range(edge_index.shape[1])
    ]
    edge_type_idx = torch.tensor(
        [mapper.edge_type2idx[et] for et in edge_type_strs], device=device
    )

    print(f"  Edge types (first 10): {edge_type_strs[:10]}")
    print(f"  Edge type indices (first 10): {edge_type_idx[:10].tolist()}")

    # Create batch indices (all nodes/edges belong to the same graph)
    batch_node = torch.zeros(num_atoms, dtype=torch.long, device=device)
    batch_edge = torch.zeros(edge_index.shape[1], dtype=torch.long, device=device)
    print(f"\n  Batch indices: nodes {batch_node.shape}, edges {batch_edge.shape}")

    # =============================================================================
    # DEFINE MINIMAL NETWORK
    # =============================================================================
    print("\n[NETWORK] Defining minimal E(3)-equivariant network...")

    # Use provided hidden_irreps or build them automatically
    if CONFIG["hidden_irreps"] is not None:
        hidden_irreps = Irreps(CONFIG["hidden_irreps"])
        print(f"  Using provided hidden irreps: {hidden_irreps}")
    else:
        hidden_irreps = build_hidden_irreps(
            l_max=CONFIG["l_max"], base_dim=CONFIG["hidden_dim"], use_odd_features=True
        )
        print(f"  Built hidden irreps: {hidden_irreps}")
        # Store the constructed irreps in config for checkpoint saving
        CONFIG["hidden_irreps"] = str(hidden_irreps)

    # Instantiate network
    print("\nInstantiating network...")
    num_elements = len(orbital_cfg.elements())
    num_edge_types = num_elements**2
    network = MinimalNetwork(
        num_elements=num_elements,
        n_radial=CONFIG["n_radial"],
        num_edge_types=num_edge_types,
        hidden_irreps=hidden_irreps,
        sh_irreps=sh_irreps,
        num_layers=CONFIG["num_layers"],
        mapper=mapper,
    ).to(device)

    print("\n✓ Network architecture complete!")

    # =============================================================================
    # TRAINING LOOP
    # =============================================================================
    print("\n" + "=" * 80)
    print("TRAINING TO OVERFIT")
    print("=" * 80)

    optimizer = Adam(network.parameters(), lr=CONFIG["lr"])

    # Training history
    history = {
        "loss": [],
        "mse_H": [],
        "mae_H": [],
    }

    # Track best model
    best_loss = float("inf")
    best_epoch = 0

    print(f"\nOptimizer: Adam(lr={CONFIG['lr']})")
    print(f"Training for {CONFIG['num_epochs']} epochs...\n")

    for epoch in range(CONFIG["num_epochs"]):
        network.train()
        optimizer.zero_grad()

        # Forward pass (suppress detailed logging during training)
        if epoch % CONFIG["log_interval"] == 0:
            print(f"\n{'=' * 60}")
            print(f"EPOCH {epoch + 1}/{CONFIG['num_epochs']}")
            print(f"{'=' * 60}")

        # Temporarily suppress forward pass logging
        verbose = (epoch % CONFIG["log_interval"] == 0) and (
            epoch < 10 or epoch % (CONFIG["log_interval"]) == 0
        )

        # Enable activation logging only during log intervals
        log_activations = epoch % CONFIG["log_interval"] == 0

        if not verbose:
            # Silence print by redirecting to nowhere temporarily
            old_stdout = sys.stdout
            sys.stdout = open(os.devnull, "w")

        pred_raw = network(
            node_type_idx,
            edge_type_idx,
            edge_index,
            edge_shift,
            edge_length_emb,
            edge_sh,
            batch_node,
            batch_edge,
            log_to_wandb=log_activations,
        )

        if not verbose:
            sys.stdout.close()
            sys.stdout = old_stdout

        # Wrap predictions into IrrepsBlockData then convert to matrix blocks
        from collections import Counter
        from data.block_matrix import IrrepsBlockData

        pair_vec_H = {}
        pair_edges_dict = {}
        lookup_dict = {}

        for key, payload in pred_raw.items():
            pair_vec_H[key] = payload["vectors"]
            pair_edges_dict[key] = payload["edges"]

            for idx, edge_5d in enumerate(payload["edges"].t()):
                sx, sy, sz, i, j = edge_5d.tolist()
                lookup_dict[(int(sx), int(sy), int(sz), int(i), int(j))] = (key, idx)

        pred_H_irreps = IrrepsBlockData(
            atoms=tuple(atoms_list),
            atom_counts=Counter(atoms_list),
            pair_vectors=pair_vec_H,
            pair_edges=pair_edges_dict,
            lookup=lookup_dict,
            orbital_cfg=orbital_cfg,
        )

        # Convert to matrix blocks (train_target = "matrix")
        pred_H_matrix = pred_H_irreps.to_blocks(mapper)

        # Compute loss on matrix blocks
        loss_H = 0.0

        for key in target_H_matrix.pair_blocks.keys():
            if key in pred_H_matrix.pair_blocks:
                # Match sizes (predictions might have more edges due to cutoff)
                pred_blocks = pred_H_matrix.pair_blocks[key]
                targ_blocks = target_H_matrix.pair_blocks[key]
                min_n = min(pred_blocks.shape[0], targ_blocks.shape[0])

                loss_H += F.mse_loss(pred_blocks[:min_n], targ_blocks[:min_n])

        # Total loss (only Hamiltonian)
        loss = loss_H

        # Backward
        loss.backward()
        optimizer.step()

        # Log training loss at every step
        wandb.log({"train/loss_step": loss.item(), "epoch": epoch})

        # Logging
        if epoch % CONFIG["log_interval"] == 0:
            # Compute detailed metrics
            detailed_metrics = compute_detailed_metrics(
                pred_H_matrix, target_H_matrix, overlap_e3nn
            )

            # Legacy mae_H for history
            mae_H = detailed_metrics["mae"]

            history["loss"].append(loss.item())
            history["mse_H"].append(loss_H.item())
            history["mae_H"].append(mae_H)

            # Log to console
            print(f"\n[METRICS]")
            print(f"  Loss (MSE):           {loss.item():.6e}")
            print(f"  MAE H:                {detailed_metrics['mae']:.6e}")
            print(f"  MSE H:                {detailed_metrics['mse']:.6e}")
            print(f"  MAE H (modified):     {detailed_metrics['mae_mod']:.6e}")
            print(f"  MSE H (modified):     {detailed_metrics['mse_mod']:.6e}")
            print(f"  mu_H:                 {detailed_metrics['mu_H']:.6e}")
            print(f"  Correction MAE:       {detailed_metrics['correction_mae']:.6e}")
            print(f"  Correction MSE:       {detailed_metrics['correction_mse']:.6e}")

            # Log to WandB
            wandb.log(
                {
                    "epoch": epoch,
                    "loss": loss.item(),
                    "mse_H": detailed_metrics["mse"],
                    "mae_H": detailed_metrics["mae"],
                    "mae_H_mod": detailed_metrics["mae_mod"],
                    "mse_H_mod": detailed_metrics["mse_mod"],
                    "mu_H": detailed_metrics["mu_H"],
                    "correction_mae": detailed_metrics["correction_mae"],
                    "correction_mse": detailed_metrics["correction_mse"],
                }
            )

            # Save best model
            if loss.item() < best_loss:
                best_loss = loss.item()
                best_epoch = epoch
                best_model_path = run_checkpoint_dir / "best_model.pt"
                torch.save(
                    {
                        "epoch": epoch,
                        "model_state_dict": network.state_dict(),
                        "optimizer_state_dict": optimizer.state_dict(),
                        "loss": loss.item(),
                        "mae_H": mae_H,
                        "config": CONFIG,
                        "metrics": detailed_metrics,
                    },
                    best_model_path,
                )
                print(
                    f"  ✓ Best model saved to {best_model_path.name} (loss: {loss.item():.6e})"
                )

            # Check for convergence
            if loss.item() < 1e-10:
                print(f"\n✓ Converged! Loss below 1e-8 at epoch {epoch + 1}")
                break

    # =============================================================================
    # FINAL EVALUATION
    # =============================================================================
    print("\n" + "=" * 80)
    print("FINAL EVALUATION")
    print("=" * 80)

    network.eval()
    with torch.no_grad():
        pred_raw = network(
            node_type_idx,
            edge_type_idx,
            edge_index,
            edge_shift,
            edge_length_emb,
            edge_sh,
            batch_node,
            batch_edge,
        )

        # Reconstruct full predictions
        pair_vec_H = {}
        pair_edges_dict = {}
        lookup_dict = {}

        for key, payload in pred_raw.items():
            pair_vec_H[key] = payload["vectors"]
            pair_edges_dict[key] = payload["edges"]

            for idx, edge_5d in enumerate(payload["edges"].t()):
                sx, sy, sz, i, j = edge_5d.tolist()
                lookup_dict[(int(sx), int(sy), int(sz), int(i), int(j))] = (key, idx)

        pred_H_irreps = IrrepsBlockData(
            atoms=tuple(atoms_list),
            atom_counts=Counter(atoms_list),
            pair_vectors=pair_vec_H,
            pair_edges=pair_edges_dict,
            lookup=lookup_dict,
            orbital_cfg=orbital_cfg,
        )

        # Convert to blocks
        pred_H_matrix = pred_H_irreps.to_blocks(mapper)

        # Compute detailed metrics for final evaluation
        final_detailed_metrics = compute_detailed_metrics(
            pred_H_matrix, target_H_matrix, overlap_e3nn
        )

        print("\n[FINAL PREDICTIONS - Hamiltonian]")
        print(f"\n  Overall Metrics:")
        print(f"    MAE H:                {final_detailed_metrics['mae']:.6e}")
        print(f"    MSE H:                {final_detailed_metrics['mse']:.6e}")
        print(f"    MAE H (modified):     {final_detailed_metrics['mae_mod']:.6e}")
        print(f"    MSE H (modified):     {final_detailed_metrics['mse_mod']:.6e}")
        print(f"    mu_H:                 {final_detailed_metrics['mu_H']:.6e}")
        print(
            f"    Correction MAE:       {final_detailed_metrics['correction_mae']:.6e}"
        )
        print(
            f"    Correction MSE:       {final_detailed_metrics['correction_mse']:.6e}"
        )

        final_metrics = {
            "final/mae_H": final_detailed_metrics["mae"],
            "final/mse_H": final_detailed_metrics["mse"],
            "final/mae_H_mod": final_detailed_metrics["mae_mod"],
            "final/mse_H_mod": final_detailed_metrics["mse_mod"],
            "final/mu_H": final_detailed_metrics["mu_H"],
            "final/correction_mae": final_detailed_metrics["correction_mae"],
            "final/correction_mse": final_detailed_metrics["correction_mse"],
        }

        print("\n  Per-block Metrics:")
        for key in pred_H_matrix.pair_blocks.keys():
            pred_block = pred_H_matrix.pair_blocks[key]
            true_block = target_H_matrix.pair_blocks[key]
            min_n = min(pred_block.shape[0], true_block.shape[0])

            block_mse = F.mse_loss(pred_block[:min_n], true_block[:min_n]).item()
            block_mae = torch.mean(
                torch.abs(pred_block[:min_n] - true_block[:min_n])
            ).item()

            pair_irreps = mapper.get_pair_irreps(key)

            print(f"\n  {key}:")
            print(f"    Block shape: {pred_block.shape}, Irreps: {pair_irreps}")
            print(f"    MSE: {block_mse:.6e}")
            print(f"    MAE: {block_mae:.6e}")
            print(
                f"    Relative error: {block_mae / (torch.abs(true_block[:min_n]).mean().item() + 1e-10):.6%}"
            )

            final_metrics[f"final/{key}_mse"] = block_mse
            final_metrics[f"final/{key}_mae"] = block_mae

        # Log final metrics to WandB
        wandb.log(final_metrics)

    # Save final model
    final_model_path = run_checkpoint_dir / "final_model.pt"
    torch.save(
        {
            "epoch": epoch,
            "model_state_dict": network.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "loss": history["loss"][-1],
            "mae_H": history["mae_H"][-1],
            "config": CONFIG,
            "history": history,
            "final_metrics": final_detailed_metrics,
        },
        final_model_path,
    )

    print("\n" + "=" * 80)
    print("STUDY COMPLETE")
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Total training epochs: {epoch + 1}")
    print(f"Final loss: {history['loss'][-1]:.6e}")
    print(f"Best loss: {min(history['loss']):.6e} (epoch {best_epoch + 1})")
    print(f"\nCheckpoints saved to: {run_checkpoint_dir}")
    print(f"  Best model: {run_checkpoint_dir / 'best_model.pt'}")
    print(f"  Final model: {final_model_path}")
    print("\n✓ Minimal overfit study finished successfully!")

    # Finish WandB run
    wandb.finish()
