"""
Minimal E(3)-Equivariant Network Study: Overfit Single Water Structure
=======================================================================

This study implements the SIMPLEST possible E(3)-equivariant GNN from scratch
to overfit on a single H2O snapshot. Everything is done explicitly without
importing high-level classes like E3GNN or E3GNNDataset.

Goal: Achieve highest possible accuracy through aggressive overfitting.

Architecture:
- Simple node encoder: element embedding -> scalars
- Simple edge encoder: distance + spherical harmonics
- 1-2 message passing layers with basic tensor products
- Simple head: edge features -> matrix blocks via BlockIrrepMapper

Verbose logging at every step for educational purposes.
"""

# Standard library imports
import sys
import os
from pathlib import Path
import argparse
import time
from collections import Counter

# Third-party imports
import torch
import torch.nn.functional as F
from torch.optim import Adam
from torch.nn.utils import clip_grad_norm_
from torch.optim.lr_scheduler import ReduceLROnPlateau
from e3nn.o3 import Irreps, spherical_harmonics, Irrep
from e3nn.math import soft_one_hot_linspace
from ase import Atoms
from ase.neighborlist import neighbor_list

# Project-specific imports
from net.common import build_hidden_irreps
from data.snapshot import Snapshot
from core.block_irrep_mapper import BlockIrrepMapper
from data.block_matrix import IrrepsBlockData, BlockMatrix
import wandb
from common import (
    MinimalNetwork,
    compute_detailed_metrics,
    save_hamiltonian_frame_to_disk,
    compile_frames_to_video,
)


if __name__ == "__main__":
    # =============================================================================
    # PARSE ARGUMENTS
    # =============================================================================
    parser = argparse.ArgumentParser(
        description="Minimal E(3)-Equivariant Network: Overfit Single Water Structure"
    )
    parser.add_argument(
        "--data-path",
        type=str,
        default=str("data/small/H2O/original/H2O.matrix"),
        help="Path to the matrix file",
    )
    parser.add_argument(
        "--info-path",
        type=str,
        default=str("data/small/H2O/original/H2O.info.out"),
        help="Path to the info file",
    )
    parser.add_argument(
        "--hidden-dim",
        type=int,
        default=32,
        help="Hidden dimension for features (used if --hidden-irreps not provided)",
    )
    parser.add_argument(
        "--l-max",
        type=int,
        default=2,
        help="Maximum angular momentum (used if --hidden-irreps not provided)",
    )
    parser.add_argument(
        "--hidden-irreps",
        type=str,
        default=None,
        help="Hidden irreps string (e.g., '32x0e+32x1o+32x2e'). If not provided, will be constructed using build_hidden_irreps with --hidden-dim and --l-max",
    )
    parser.add_argument(
        "--num-layers",
        type=int,
        default=2,
        help="Number of message passing layers",
    )
    parser.add_argument(
        "--cutoff-radius",
        type=float,
        default=8.0,
        help="Cutoff radius in Angstroms",
    )
    parser.add_argument(
        "--n-radial",
        type=int,
        default=16,
        help="Number of radial basis functions",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-2,
        help="Learning rate",
    )
    parser.add_argument(
        "--num-epochs",
        type=int,
        default=10000,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--log-interval",
        type=int,
        default=200,
        help="Interval for logging",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device to use (cuda or cpu)",
    )
    parser.add_argument(
        "--checkpoint-dir",
        type=str,
        default=str("studies/minimal_overfit_study/checkpoints"),
        help="Directory to save checkpoints",
    )
    parser.add_argument(
        "--run-name",
        type=str,
        default=None,
        help="WandB run name (default: auto-generated by WandB)",
    )
    parser.add_argument(
        "--grad-clip",
        type=float,
        default=1.0,
        help="Gradient clipping max norm (default: 1.0, set to 0 to disable)",
    )
    parser.add_argument(
        "--lr-factor",
        type=float,
        default=0.5,
        help="ReduceLROnPlateau factor (default: 0.5)",
    )
    parser.add_argument(
        "--lr-patience",
        type=int,
        default=20,
        help="ReduceLROnPlateau patience (default: 20)",
    )
    parser.add_argument(
        "--partial-train",
        type=str,
        default=None,
        choices=["diag", "offdiag", None],
        help="Train on partial data: 'diag' (diagonal blocks only), 'offdiag' (off-diagonal only), or None (all blocks)",
    )
    parser.add_argument(
        "--train-on-irrep-parts",
        action="store_true",
        help="Decompose loss into per-irrep contributions (log to partial/* in wandb)",
    )

    args = parser.parse_args()

    # =============================================================================
    # CONFIGURATION
    # =============================================================================
    print("=" * 80)
    print("MINIMAL WATER OVERFIT STUDY - EXPLICIT IMPLEMENTATION")
    print("=" * 80)
    print("\n[CONFIG] Setting up hyperparameters...")

    CONFIG = {
        # Data
        "data_path": Path(args.data_path),
        "info_path": Path(args.info_path),
        # Network architecture
        "hidden_dim": args.hidden_dim,
        "l_max": args.l_max,
        "hidden_irreps": args.hidden_irreps,  # Can be None
        "num_layers": args.num_layers,
        "cutoff_radius": args.cutoff_radius,
        "n_radial": args.n_radial,
        # Training
        "lr": args.lr,
        "num_epochs": args.num_epochs,
        "log_interval": args.log_interval,
        "grad_clip": args.grad_clip,
        "partial_train": args.partial_train,
        "train_on_irrep_parts": args.train_on_irrep_parts,
        "lr_factor": args.lr_factor,
        "lr_patience": args.lr_patience,
        # Device
        "device": args.device,
        # Target
        "train_target": "matrix",
        # Checkpointing
        "checkpoint_dir": Path(args.checkpoint_dir),
    }

    # Initialize WandB
    wandb_kwargs = {
        "project": "mandala-minimal-overfit-study",
        "config": CONFIG,
    }
    if args.run_name is not None:
        wandb_kwargs["name"] = args.run_name
    wandb.init(**wandb_kwargs)

    # Create run-specific checkpoint directory
    run_name = wandb.run.name
    run_checkpoint_dir = CONFIG["checkpoint_dir"] / run_name
    run_checkpoint_dir.mkdir(parents=True, exist_ok=True)
    print(f"  Run-specific checkpoint directory: {run_checkpoint_dir}")

    # Create frame output directory for video frames
    frame_output_dir = run_checkpoint_dir / "frames"
    frame_output_dir.mkdir(parents=True, exist_ok=True)
    print(f"  Frame output directory: {frame_output_dir}")

    print(f"  Device: {CONFIG['device']}")
    print(f"  Hidden dim: {CONFIG['hidden_dim']}")
    print(f"  L_max: {CONFIG['l_max']}")
    print(f"  Num layers: {CONFIG['num_layers']}")
    print(f"  Cutoff radius: {CONFIG['cutoff_radius']} Å")
    print(f"  Learning rate: {CONFIG['lr']}")
    print(f"  Epochs: {CONFIG['num_epochs']}")
    print(f"  Checkpoint directory: {CONFIG['checkpoint_dir']}")
    if CONFIG["grad_clip"] > 0:
        print(f"  Gradient clipping: {CONFIG['grad_clip']}")
    else:
        print(f"  Gradient clipping: disabled")
    if CONFIG["partial_train"] is not None:
        print(f"  Partial training: {CONFIG['partial_train']} blocks only")
    else:
        print(f"  Partial training: disabled (training on all blocks)")
    if CONFIG["train_on_irrep_parts"]:
        print(f"  Train on irrep parts: enabled (decomposed per-irrep loss)")
    else:
        print(f"  Train on irrep parts: disabled (standard loss)")

    device = torch.device(CONFIG["device"])

    # =============================================================================
    # LOAD DATA
    # =============================================================================
    print("\n[DATA] Loading single water snapshot...")

    # Load snapshot using Snapshot.from_openmx
    print(f"  Matrix file: {CONFIG['data_path']}")
    print(f"  Info file: {CONFIG['info_path']}")

    snapshot = Snapshot.from_openmx(
        matrix_path=CONFIG["data_path"],
        info_path=CONFIG["info_path"],
        convention="e3nn",  # Automatically converts to e3nn basis
        symmetrize_density=True,
        cutoff_radius=None,  # No filtering, we'll use all edges
        dtype=torch.float32,
    )

    print(f"\n  Snapshot loaded:")
    print(f"    Elements: {snapshot.hamiltonian.atoms}")
    print(f"    Num atoms: {len(snapshot.hamiltonian.atoms)}")
    print(f"    Positions shape: {snapshot.positions.shape}")
    print(f"    Box shape: {snapshot.box.shape if snapshot.box is not None else None}")
    print(f"    Basis: {snapshot.hamiltonian.basis}")

    print(f"\n  Matrices:")
    print(f"    Hamiltonian keys: {list(snapshot.hamiltonian.pair_blocks.keys())}")
    print(f"    Overlap keys: {list(snapshot.overlap.pair_blocks.keys())}")
    print(f"    Density keys: {list(snapshot.density.pair_blocks.keys())}")

    print(f"\n  Hamiltonian blocks:")
    for key, blocks in snapshot.hamiltonian.pair_blocks.items():
        print(
            f"    {key}: shape {blocks.shape}, edges {snapshot.hamiltonian.pair_edges[key].shape}"
        )

    # Extract components
    hamiltonian_e3nn = snapshot.hamiltonian.to(device)
    overlap_e3nn = snapshot.overlap.to(device)
    density_e3nn = snapshot.density.to(device)
    orbital_cfg = snapshot.hamiltonian.orbital_cfg
    positions = snapshot.positions.to(device)
    box = snapshot.box.to(device) if snapshot.box is not None else None
    atoms_list = list(snapshot.hamiltonian.atoms)

    print(f"\n  Orbital configuration:")
    for elem in orbital_cfg.elements():
        irreps = orbital_cfg.element_to_irreps[elem]
        print(f"    {elem}: {irreps} (dim={irreps.dim})")

    # Create BlockIrrepMapper
    print("\n[MAPPER] Creating BlockIrrepMapper...")
    mapper = BlockIrrepMapper(orbital_cfg, device=device, dtype=torch.float32)
    print(f"  Mapper edge types: {mapper.edge_types}")
    print(f"  Mapper edge_type2idx: {mapper.edge_type2idx}")

    # Store target as matrix blocks (train_target = "matrix")
    print("\n[TARGETS] Storing target as matrix blocks...")
    target_H_matrix = hamiltonian_e3nn

    print("  Target matrix blocks:")
    for key in target_H_matrix.pair_blocks.keys():
        block_shape = target_H_matrix.pair_blocks[key].shape
        edge_shape = target_H_matrix.pair_edges[key].shape
        pair_irreps = mapper.get_pair_irreps(key)
        print(
            f"    {key}: blocks {block_shape}, edges {edge_shape}, irreps {pair_irreps}"
        )

    # =============================================================================
    # BUILD GRAPH
    # =============================================================================
    print("\n[GRAPH] Constructing molecular graph...")

    num_atoms = len(atoms_list)

    print(f"  Atoms: {atoms_list}")
    print(f"  Positions (e3nn frame):\n{positions}")
    if box is not None:
        print(f"  Box (e3nn frame):\n{box}")

    # Create ASE atoms object for neighbor list
    ase_atoms = Atoms(
        symbols=atoms_list,
        positions=positions.cpu().numpy(),
        cell=box.cpu().numpy() if box is not None else None,
        pbc=box is not None,
    )

    # Find neighbors using ASE
    print(f"\n  Finding neighbors within {CONFIG['cutoff_radius']} Å...")
    src, dst, offsets = neighbor_list(
        "ijS", ase_atoms, CONFIG["cutoff_radius"], self_interaction=False
    )

    print(f"  Found {len(src)} off-diagonal edges")
    print(f"  Edge list (first 10):")
    for i in range(min(10, len(src))):
        print(f"    {src[i]} -> {dst[i]} (offset: {offsets[i]})")

    # Add self-edges
    self_src = torch.arange(num_atoms, dtype=torch.long, device=device)
    self_dst = torch.arange(num_atoms, dtype=torch.long, device=device)
    self_offsets = torch.zeros((num_atoms, 3), dtype=torch.long, device=device)

    # Combine all edges
    all_src = torch.cat([self_src, torch.from_numpy(src).to(device)])
    all_dst = torch.cat([self_dst, torch.from_numpy(dst).to(device)])
    all_offsets = torch.cat([self_offsets, torch.from_numpy(offsets).to(device).long()])

    edge_index = torch.stack([all_src, all_dst], dim=0)  # (2, E)
    edge_shift = all_offsets.T  # (3, E)

    num_self_edges = num_atoms
    print(
        f"  Total edges: {edge_index.shape[1]} ({num_self_edges} self + {edge_index.shape[1] - num_self_edges} off-diagonal)"
    )

    # Compute edge vectors and distances
    print("\n  Computing edge displacements and distances...")
    if box is not None:
        shift_float = edge_shift.T.float()
        edge_vec = (
            positions[edge_index[1]] - positions[edge_index[0]] + shift_float @ box
        )
    else:
        edge_vec = positions[edge_index[1]] - positions[edge_index[0]]

    edge_dist = torch.linalg.norm(edge_vec, dim=1)

    print(
        f"  Edge distances (Å): min={edge_dist.min().item():.3f}, max={edge_dist.max().item():.3f}, mean={edge_dist.mean().item():.3f}"
    )
    print(f"  Self-edge distances: {edge_dist[:num_self_edges]}")

    # Compute spherical harmonics
    print(f"\n  Computing spherical harmonics (l_max={CONFIG['l_max']})...")
    sh_irreps = Irreps.spherical_harmonics(CONFIG["l_max"])
    print(f"  SH irreps: {sh_irreps}")

    # Normalize edge vectors (avoid division by zero for self-edges)
    edge_vec_norm = edge_vec.clone()
    non_zero_mask = edge_dist > 1e-6
    edge_vec_norm[non_zero_mask] = edge_vec[non_zero_mask] / edge_dist[
        non_zero_mask
    ].unsqueeze(-1)

    edge_sh = spherical_harmonics(sh_irreps, edge_vec_norm, normalize=False)
    print(f"  Edge SH shape: {edge_sh.shape}")

    # Radial basis functions
    print(f"\n  Computing radial embeddings ({CONFIG['n_radial']} basis functions)...")
    edge_length_emb = soft_one_hot_linspace(
        edge_dist,
        start=0.0,
        end=CONFIG["cutoff_radius"],
        number=CONFIG["n_radial"],
        basis="gaussian",
        cutoff=False,
    )
    edge_length_emb = edge_length_emb * CONFIG["n_radial"] ** 0.5  # Normalization
    print(f"  Edge length embedding shape: {edge_length_emb.shape}")

    # Edge type indices
    print("\n  Computing edge type indices...")
    element_to_idx = {elem: idx for idx, elem in enumerate(orbital_cfg.elements())}
    print(f"  Element to index: {element_to_idx}")

    node_type_idx = torch.tensor([element_to_idx[a] for a in atoms_list], device=device)
    src_type = node_type_idx[edge_index[0]]
    dst_type = node_type_idx[edge_index[1]]

    # Create edge type strings and map to indices
    edge_type_strs = [
        f"{atoms_list[edge_index[0, i].item()]}-{atoms_list[edge_index[1, i].item()]}"
        for i in range(edge_index.shape[1])
    ]
    edge_type_idx = torch.tensor(
        [mapper.edge_type2idx[et] for et in edge_type_strs], device=device
    )

    print(f"  Edge types (first 10): {edge_type_strs[:10]}")
    print(f"  Edge type indices (first 10): {edge_type_idx[:10].tolist()}")

    # Create batch indices (all nodes/edges belong to the same graph)
    batch_node = torch.zeros(num_atoms, dtype=torch.long, device=device)
    batch_edge = torch.zeros(edge_index.shape[1], dtype=torch.long, device=device)
    print(f"\n  Batch indices: nodes {batch_node.shape}, edges {batch_edge.shape}")

    # =============================================================================
    # HELPER FUNCTIONS FOR PARTIAL TRAINING AND IRREP FILTERING
    # =============================================================================
    def filter_irreps_block_data_by_irrep(irreps_block_data, target_irrep):
        """
        Filter IrrepsBlockData to only include contributions from a specific irrep.
        All other irrep components are zeroed out.

        Args:
            irreps_block_data: IrrepsBlockData object
            target_irrep: e3nn.o3.Irrep to keep (e.g., Irrep("0e"), Irrep("1o"))

        Returns:
            Filtered IrrepsBlockData with only target_irrep contributions
        """
        # ...existing code...

        if isinstance(target_irrep, str):
            target_irrep = Irrep(target_irrep)

        filtered_vectors = {}

        for edge_type, vectors in irreps_block_data.pair_vectors.items():
            # Get pair irreps for this edge type
            pair_irreps = mapper.get_pair_irreps(edge_type)

            # Create mask for target irrep
            filtered_vec = torch.zeros_like(vectors)
            start_idx = 0

            for mul, irrep in pair_irreps:
                irrep_dim = irrep.dim * mul

                if irrep == target_irrep:
                    # Keep this irrep's contribution
                    filtered_vec[:, start_idx : start_idx + irrep_dim] = vectors[
                        :, start_idx : start_idx + irrep_dim
                    ]

                start_idx += irrep_dim

            filtered_vectors[edge_type] = filtered_vec

        return IrrepsBlockData(
            atoms=irreps_block_data.atoms,
            atom_counts=irreps_block_data.atom_counts,
            pair_vectors=filtered_vectors,
            pair_edges=irreps_block_data.pair_edges,
            lookup=irreps_block_data.lookup,
            orbital_cfg=irreps_block_data.orbital_cfg,
            basis=irreps_block_data.basis,
        )

    def get_all_irreps_in_hamiltonian(irreps_block_data):
        """
        Get list of all unique irreps present in the Hamiltonian.

        Args:
            irreps_block_data: IrrepsBlockData object

        Returns:
            List of unique Irrep objects, sorted by (l, parity)
        """

        unique_irreps = set()

        for edge_type in irreps_block_data.pair_vectors.keys():
            pair_irreps = mapper.get_pair_irreps(edge_type)
            for mul, irrep in pair_irreps:
                if mul > 0:  # Only include irreps that are actually present
                    unique_irreps.add(irrep)

        # Sort by (l, p) where p=1 for even, p=-1 for odd
        return sorted(unique_irreps, key=lambda ir: (ir.l, ir.p))

    def get_diagonal_mask(edges_5d):
        """
        Get mask for diagonal blocks (self-interactions: sx=sy=sz=0, i=j).

        Args:
            edges_5d: (5, num_edges) tensor with [sx, sy, sz, i, j]

        Returns:
            Boolean mask of shape (num_edges,) with True for diagonal blocks
        """
        sx, sy, sz, i, j = (
            edges_5d[0],
            edges_5d[1],
            edges_5d[2],
            edges_5d[3],
            edges_5d[4],
        )
        is_self_interaction = (sx == 0) & (sy == 0) & (sz == 0)
        is_same_atom = i == j
        return is_self_interaction & is_same_atom

    def filter_blocks_by_partial_train(block_matrix, partial_train):
        """
        Filter blocks based on partial_train setting.

        Args:
            block_matrix: BlockMatrix object
            partial_train: "diag", "offdiag", or None

        Returns:
            Dictionary mapping edge_type -> (filtered_blocks, mask)
        """
        if partial_train is None:
            # Return all blocks with full mask
            return {
                key: (
                    blocks,
                    torch.ones(blocks.shape[0], dtype=torch.bool, device=blocks.device),
                )
                for key, blocks in block_matrix.pair_blocks.items()
            }

        filtered_data = {}
        for key in block_matrix.pair_blocks.keys():
            blocks = block_matrix.pair_blocks[key]
            edges = block_matrix.pair_edges[key]  # (5, num_edges)

            diag_mask = get_diagonal_mask(edges)

            if partial_train == "diag":
                mask = diag_mask
            elif partial_train == "offdiag":
                mask = ~diag_mask
            else:
                mask = torch.ones(
                    blocks.shape[0], dtype=torch.bool, device=blocks.device
                )

            filtered_data[key] = (blocks, mask)

        return filtered_data

    # =============================================================================
    # DEFINE MINIMAL NETWORK
    # =============================================================================
    print("\n[NETWORK] Defining minimal E(3)-equivariant network...")

    # Use provided hidden_irreps or build them automatically
    if CONFIG["hidden_irreps"] is not None:
        hidden_irreps = Irreps(CONFIG["hidden_irreps"])
        print(f"  Using provided hidden irreps: {hidden_irreps}")
    else:
        hidden_irreps = build_hidden_irreps(
            l_max=CONFIG["l_max"], base_dim=CONFIG["hidden_dim"], use_odd_features=True
        )
        print(f"  Built hidden irreps: {hidden_irreps}")
        # Store the constructed irreps in config for checkpoint saving
        CONFIG["hidden_irreps"] = str(hidden_irreps)

    # Instantiate network
    print("\nInstantiating network...")
    num_elements = len(orbital_cfg.elements())
    num_edge_types = num_elements**2
    network = MinimalNetwork(
        num_elements=num_elements,
        n_radial=CONFIG["n_radial"],
        num_edge_types=num_edge_types,
        hidden_irreps=hidden_irreps,
        sh_irreps=sh_irreps,
        num_layers=CONFIG["num_layers"],
        mapper=mapper,
    ).to(device)

    print("\n✓ Network architecture complete!")

    # =============================================================================
    # PREPARE TARGET IN IRREPS SPACE (if needed for irrep-decomposed loss)
    # =============================================================================
    target_H_irreps = None
    all_irreps = None

    if CONFIG["train_on_irrep_parts"]:
        print("\n[IRREP DECOMPOSITION] Converting target to irreps space...")
        target_H_irreps = target_H_matrix.to_vectors(mapper)
        all_irreps = get_all_irreps_in_hamiltonian(target_H_irreps)
        print(
            f"  Found {len(all_irreps)} unique irreps: {[str(ir) for ir in all_irreps]}"
        )

    # =============================================================================
    # TRAINING LOOP
    # =============================================================================
    print("\n" + "=" * 80)
    print("TRAINING TO OVERFIT")
    print("=" * 80)

    optimizer = Adam(network.parameters(), lr=CONFIG["lr"])

    # Add ReduceLROnPlateau scheduler
    scheduler = ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=CONFIG["lr_factor"],
        patience=CONFIG["lr_patience"],
        threshold=1e-4,
        threshold_mode="rel",
        cooldown=10,
        min_lr=1e-6,
        verbose=True,
    )

    # Training history
    history = {
        "loss": [],
        "mse_H": [],
        "mae_H": [],
    }

    # Track best model
    best_loss = float("inf")
    best_epoch = 0

    # Track timing
    last_log_time = time.time()

    print(f"\nOptimizer: Adam(lr={CONFIG['lr']})")
    print(f"Training for {CONFIG['num_epochs']} epochs...\n")

    try:
        for epoch in range(CONFIG["num_epochs"]):
            network.train()
            optimizer.zero_grad()

            # Forward pass (suppress detailed logging during training)
            if epoch % CONFIG["log_interval"] == 0:
                print(f"\n{'=' * 60}")
                print(f"EPOCH {epoch + 1}/{CONFIG['num_epochs']}")
                print(f"{'=' * 60}")

            # Temporarily suppress forward pass logging
            verbose = (epoch % CONFIG["log_interval"] == 0) and (
                epoch < 10 or epoch % (CONFIG["log_interval"]) == 0
            )

            # Enable activation logging only during log intervals
            log_activations = epoch % CONFIG["log_interval"] == 0

            if not verbose:
                # Silence print by redirecting to nowhere temporarily
                old_stdout = sys.stdout
                sys.stdout = open(os.devnull, "w")

            pred_raw = network(
                node_type_idx,
                edge_type_idx,
                edge_index,
                edge_shift,
                edge_length_emb,
                edge_sh,
                batch_node,
                batch_edge,
                log_to_wandb=log_activations,
            )

            if not verbose:
                sys.stdout.close()
                sys.stdout = old_stdout

            # Wrap predictions into IrrepsBlockData then convert to matrix blocks

            pair_vec_H = {}
            pair_edges_dict = {}
            lookup_dict = {}

            for key, payload in pred_raw.items():
                pair_vec_H[key] = payload["vectors"]
                pair_edges_dict[key] = payload["edges"]

                for idx, edge_5d in enumerate(payload["edges"].t()):
                    sx, sy, sz, i, j = edge_5d.tolist()
                    lookup_dict[(int(sx), int(sy), int(sz), int(i), int(j))] = (
                        key,
                        idx,
                    )

            pred_H_irreps = IrrepsBlockData(
                atoms=tuple(atoms_list),
                atom_counts=Counter(atoms_list),
                pair_vectors=pair_vec_H,
                pair_edges=pair_edges_dict,
                lookup=lookup_dict,
                orbital_cfg=orbital_cfg,
                basis=target_H_matrix.basis,
            )

            # Convert to matrix blocks (train_target = "matrix")
            pred_H_matrix = pred_H_irreps.to_blocks(mapper)

            # Compute loss - either standard or per-irrep decomposed
            if CONFIG["train_on_irrep_parts"]:
                # Per-irrep decomposed loss
                loss_H = 0.0
                irrep_losses = {}
                irrep_abs = {}
                irrep_rel = {}
                # small epsilon to avoid division by zero when computing relative error
                _REL_EPS = 1e-12

                for irrep in all_irreps:
                    # Filter both prediction and target by this irrep
                    pred_irrep_filtered = filter_irreps_block_data_by_irrep(
                        pred_H_irreps, irrep
                    )
                    target_irrep_filtered = filter_irreps_block_data_by_irrep(
                        target_H_irreps, irrep
                    )

                    # Convert to matrix blocks
                    pred_irrep_blocks = pred_irrep_filtered.to_blocks(mapper)
                    target_irrep_blocks = target_irrep_filtered.to_blocks(mapper)

                    # Apply partial_train filtering
                    filtered_target_irrep = filter_blocks_by_partial_train(
                        target_irrep_blocks, CONFIG["partial_train"]
                    )

                    # Compute loss for this irrep and absolute/relative contributions
                    irrep_loss = 0.0
                    abs_sum = 0.0
                    targ_abs_sum = 0.0
                    elem_count = 0

                    for key in target_irrep_blocks.pair_blocks.keys():
                        if key in pred_irrep_blocks.pair_blocks:
                            targ_blocks_full = target_irrep_blocks.pair_blocks[key]
                            _, mask = filtered_target_irrep[key]

                            pred_blocks = pred_irrep_blocks.pair_blocks[key]
                            min_n = min(pred_blocks.shape[0], targ_blocks_full.shape[0])

                            mask = mask[:min_n]
                            if mask.any():
                                pred_blocks_filtered = pred_blocks[:min_n][mask]
                                targ_blocks_filtered = targ_blocks_full[:min_n][mask]
                                irrep_loss += F.mse_loss(
                                    pred_blocks_filtered, targ_blocks_filtered
                                )

                                # Absolute magnitude of error and target magnitude
                                diff = pred_blocks_filtered - targ_blocks_filtered
                                abs_sum += float(torch.sum(torch.abs(diff)).item())
                                targ_abs_sum += float(
                                    torch.sum(torch.abs(targ_blocks_filtered)).item()
                                )
                                elem_count += int(pred_blocks_filtered.numel())

                    irrep_str = str(irrep)
                    irrep_losses[irrep_str] = irrep_loss
                    loss_H += irrep_loss

                    # Mean absolute error for this irrep (avoid division by zero)
                    mean_abs = abs_sum / elem_count if elem_count > 0 else 0.0
                    rel = abs_sum / (targ_abs_sum + _REL_EPS)

                    irrep_abs[irrep_str] = mean_abs
                    irrep_rel[irrep_str] = rel
            else:
                # Standard loss computation
                loss_H = 0.0
                filtered_target = filter_blocks_by_partial_train(
                    target_H_matrix, CONFIG["partial_train"]
                )

                for key in target_H_matrix.pair_blocks.keys():
                    if key in pred_H_matrix.pair_blocks:
                        # Get filtered target blocks and mask
                        targ_blocks_full = target_H_matrix.pair_blocks[key]
                        _, mask = filtered_target[key]

                        # Match sizes (predictions might have fewer edges due to cutoff)
                        pred_blocks = pred_H_matrix.pair_blocks[key]
                        min_n = min(pred_blocks.shape[0], targ_blocks_full.shape[0])

                        # Apply mask to select only relevant blocks
                        mask = mask[:min_n]
                        if mask.any():
                            pred_blocks_filtered = pred_blocks[:min_n][mask]
                            targ_blocks_filtered = targ_blocks_full[:min_n][mask]
                            loss_H += F.mse_loss(
                                pred_blocks_filtered, targ_blocks_filtered
                            )

            # Total loss (only Hamiltonian)
            loss = loss_H

            # Step scheduler (ReduceLROnPlateau needs validation loss, so we use training loss here)
            scheduler.step(loss)

            # Log current learning rate
            current_lr = optimizer.param_groups[0]["lr"]
            wandb.log({"lr": current_lr, "epoch": epoch})
            # Check for NaN or Inf in loss before backward pass
            if torch.isnan(loss) or torch.isinf(loss):
                print(f"\n{'='*80}")
                print(f"❌ TRAINING FAILED at epoch {epoch + 1}")
                print(f"{'='*80}")
                if torch.isnan(loss):
                    print(f"Loss is NaN: {loss.item()}")
                    print("This indicates numerical instability in the forward pass.")
                else:
                    print(f"Loss is Inf: {loss.item()}")
                    print(
                        "Loss has exploded. Try reducing learning rate or adding regularization."
                    )
                print(
                    f"\nLast valid loss (epoch {epoch}): {history['loss'][-1] if history['loss'] else 'N/A'}"
                )
                print(
                    f"\nTraining stopped. Checkpoint saved at epoch {best_epoch + 1} with loss {best_loss:.6e}"
                )
                print(f"{'='*80}\n")
                wandb.log(
                    {
                        "training_failed": True,
                        "failure_epoch": epoch,
                        "failure_type": "NaN" if torch.isnan(loss) else "Inf",
                    }
                )
                break

            # Backward
            loss.backward()

            # Gradient clipping to prevent exploding gradients
            if CONFIG["grad_clip"] > 0:
                grad_norm = clip_grad_norm_(network.parameters(), CONFIG["grad_clip"])
                # Log gradient norm periodically
                if epoch % CONFIG["log_interval"] == 0:
                    wandb.log({"grad_norm": grad_norm.item(), "epoch": epoch})

            # Check for NaN/Inf in gradients
            has_nan_grad = False
            for name, param in network.named_parameters():
                if param.grad is not None:
                    if torch.isnan(param.grad).any() or torch.isinf(param.grad).any():
                        print(f"\n{'='*80}")
                        print(f"❌ TRAINING FAILED at epoch {epoch + 1}")
                        print(f"{'='*80}")
                        print(f"Gradient contains NaN or Inf in parameter: {name}")
                        print(
                            f"This indicates numerical instability in the backward pass."
                        )
                        print(f"\nSuggestions:")
                        print(f"  - Reduce learning rate (current: {CONFIG['lr']})")
                        print(
                            f"  - Increase gradient clipping (current: {CONFIG['grad_clip']})"
                        )
                        print(f"  - Check if irreps contain invalid combinations")
                        print(
                            f"\nLast valid loss (epoch {epoch}): {history['loss'][-1] if history['loss'] else 'N/A'}"
                        )
                        print(
                            f"Training stopped. Checkpoint saved at epoch {best_epoch + 1} with loss {best_loss:.6e}"
                        )
                        print(f"{'='*80}\n")
                        wandb.log(
                            {
                                "training_failed": True,
                                "failure_epoch": epoch,
                                "failure_type": "gradient_nan_inf",
                                "failed_param": name,
                            }
                        )
                        has_nan_grad = True
                        break

            if has_nan_grad:
                break

            optimizer.step()

            # Log training loss at every step
            step_log = {
                "train/loss_step": loss.item(),
                "epoch": epoch,
                "lr": current_lr,
            }

            # Log per-irrep losses if enabled
            if CONFIG["train_on_irrep_parts"]:
                for irrep_str, irrep_loss in irrep_losses.items():
                    step_log[f"partial/{irrep_str}"] = irrep_loss.item()
                    # Log mean absolute error and relative error for this irrep
                    step_log[f"partial_abs/{irrep_str}"] = irrep_abs.get(irrep_str, 0.0)
                    step_log[f"partial_rel/{irrep_str}"] = irrep_rel.get(irrep_str, 0.0)

            wandb.log(step_log)

            # Logging
            if epoch % CONFIG["log_interval"] == 0:
                # Compute detailed metrics with filtering
                # First filter both predictions and targets
                filtered_pred = filter_blocks_by_partial_train(
                    pred_H_matrix, CONFIG["partial_train"]
                )
                filtered_target = filter_blocks_by_partial_train(
                    target_H_matrix, CONFIG["partial_train"]
                )
                filtered_overlap = filter_blocks_by_partial_train(
                    overlap_e3nn, CONFIG["partial_train"]
                )

                # Create filtered versions for metrics computation

                pred_filtered_blocks = {}
                target_filtered_blocks = {}
                overlap_filtered_blocks = {}

                for key in target_H_matrix.pair_blocks.keys():
                    if key in pred_H_matrix.pair_blocks:
                        pred_full, pred_mask = filtered_pred[key]
                        targ_full, targ_mask = filtered_target[key]
                        ovlp_full, ovlp_mask = filtered_overlap[key]

                        min_n = min(
                            pred_full.shape[0], targ_full.shape[0], ovlp_full.shape[0]
                        )
                        mask = pred_mask[:min_n] & targ_mask[:min_n] & ovlp_mask[:min_n]

                        if mask.any():
                            pred_filtered_blocks[key] = pred_full[:min_n][mask]
                            target_filtered_blocks[key] = targ_full[:min_n][mask]
                            overlap_filtered_blocks[key] = ovlp_full[:min_n][mask]

                # Create temporary BlockMatrix objects for metrics computation
                pred_filtered = BlockMatrix(
                    atoms=target_H_matrix.atoms,
                    atom_counts=target_H_matrix.atom_counts,
                    pair_blocks=pred_filtered_blocks,
                    pair_edges={
                        key: target_H_matrix.pair_edges[key]
                        for key in pred_filtered_blocks.keys()
                    },
                    lookup=target_H_matrix.lookup,
                    orbital_cfg=target_H_matrix.orbital_cfg,
                    basis=target_H_matrix.basis,
                )
                target_filtered = BlockMatrix(
                    atoms=target_H_matrix.atoms,
                    atom_counts=target_H_matrix.atom_counts,
                    pair_blocks=target_filtered_blocks,
                    pair_edges={
                        key: target_H_matrix.pair_edges[key]
                        for key in target_filtered_blocks.keys()
                    },
                    lookup=target_H_matrix.lookup,
                    orbital_cfg=target_H_matrix.orbital_cfg,
                    basis=target_H_matrix.basis,
                )
                overlap_filtered = BlockMatrix(
                    atoms=overlap_e3nn.atoms,
                    atom_counts=overlap_e3nn.atom_counts,
                    pair_blocks=overlap_filtered_blocks,
                    pair_edges={
                        key: overlap_e3nn.pair_edges[key]
                        for key in overlap_filtered_blocks.keys()
                    },
                    lookup=overlap_e3nn.lookup,
                    orbital_cfg=overlap_e3nn.orbital_cfg,
                    basis=overlap_e3nn.basis,
                )

                detailed_metrics = compute_detailed_metrics(
                    pred_filtered, target_filtered, overlap_filtered
                )

                # mae_H for history
                mae_H = detailed_metrics["mae"]

                history["loss"].append(loss.item())
                history["mse_H"].append(loss_H.item())
                history["mae_H"].append(mae_H)

                # Calculate timing
                current_time = time.time()
                time_elapsed = current_time - last_log_time
                epochs_since_last_log = CONFIG["log_interval"] if epoch > 0 else 1
                avg_epoch_time = time_elapsed / epochs_since_last_log
                last_log_time = current_time

                # Log to console
                print(f"\n[METRICS]")
                print(
                    f"  Avg epoch time:       {avg_epoch_time:.3f}s ({epochs_since_last_log} epochs in {time_elapsed:.1f}s)"
                )
                print(f"  Loss (MSE):           {loss.item():.6e}")

                # Print per-irrep loss contributions if enabled
                if CONFIG["train_on_irrep_parts"]:
                    print(f"\n  Per-Irrep Loss Contributions:")
                    # Sort irreps by loss (descending) for better readability
                    sorted_irreps = sorted(
                        irrep_losses.items(), key=lambda x: x[1].item(), reverse=True
                    )
                    total_loss_check = sum(
                        irrep_loss.item() for _, irrep_loss in sorted_irreps
                    )
                    for irrep_str, irrep_loss in sorted_irreps:
                        percentage = (
                            (irrep_loss.item() / total_loss_check * 100)
                            if total_loss_check > 0
                            else 0
                        )
                        rel_val = (
                            irrep_rel.get(irrep_str, 0.0)
                            if "irrep_rel" in locals()
                            else 0.0
                        )
                        print(
                            f"    {irrep_str:4s}: {irrep_loss.item():.6e} ({percentage:5.1f}%)  rel: {rel_val:.3%}"
                        )

                print(f"  MAE H:                {detailed_metrics['mae']:.6e}")
                print(f"  MSE H:                {detailed_metrics['mse']:.6e}")
                print(f"  MAE H (modified):     {detailed_metrics['mae_mod']:.6e}")
                print(f"  MSE H (modified):     {detailed_metrics['mse_mod']:.6e}")
                print(f"  mu_H:                 {detailed_metrics['mu_H']:.6e}")
                print(
                    f"  Correction MAE:       {detailed_metrics['correction_mae']:.6e}"
                )
                print(
                    f"  Correction MSE:       {detailed_metrics['correction_mse']:.6e}"
                )

                # Log to WandB
                wandb.log(
                    {
                        "epoch": epoch,
                        "loss": loss.item(),
                        "mse_H": detailed_metrics["mse"],
                        "mae_H": detailed_metrics["mae"],
                        "mae_H_mod": detailed_metrics["mae_mod"],
                        "mse_H_mod": detailed_metrics["mse_mod"],
                        "mu_H": detailed_metrics["mu_H"],
                        "correction_mae": detailed_metrics["correction_mae"],
                        "correction_mse": detailed_metrics["correction_mse"],
                    }
                )

                # Save best model
                if loss.item() < best_loss:
                    best_loss = loss.item()
                    best_epoch = epoch
                    best_model_path = run_checkpoint_dir / "best_model.pt"
                    torch.save(
                        {
                            "epoch": epoch,
                            "model_state_dict": network.state_dict(),
                            "optimizer_state_dict": optimizer.state_dict(),
                            "loss": loss.item(),
                            "mae_H": mae_H,
                            "config": CONFIG,
                            "metrics": detailed_metrics,
                        },
                        best_model_path,
                    )
                    print(
                        f"  ✓ Best model saved to {best_model_path.name} (loss: {loss.item():.6e})"
                    )

                # Save frame for video at every log interval
                try:
                    save_hamiltonian_frame_to_disk(
                        pred_H_matrix,
                        target_H_matrix,
                        overlap_e3nn,
                        list(snapshot.hamiltonian.atoms),
                        orbital_cfg,
                        frame_output_dir,
                        epoch,
                        sx=0,
                        sy=0,
                        sz=0,
                        dynamic_range=False,
                        partial_train=CONFIG["partial_train"],
                        percentile=99.0,
                    )
                except Exception as e:
                    print(f"  ⚠️  Warning: Could not save frame for epoch {epoch}: {e}")

                # Check for convergence
                if loss.item() < 1e-10:
                    print(f"\n✓ Converged! Loss below 1e-8 at epoch {epoch + 1}")
                    break
    except KeyboardInterrupt:
        print(
            "\n[INFO] Training interrupted by user (Ctrl-C). Proceeding to final evaluation and saving..."
        )

    # =============================================================================
    # FINAL EVALUATION
    # =============================================================================
    print("\n" + "=" * 80)
    print("FINAL EVALUATION")
    print("=" * 80)

    network.eval()
    with torch.no_grad():
        pred_raw = network(
            node_type_idx,
            edge_type_idx,
            edge_index,
            edge_shift,
            edge_length_emb,
            edge_sh,
            batch_node,
            batch_edge,
        )

        # Reconstruct full predictions
        pair_vec_H = {}
        pair_edges_dict = {}
        lookup_dict = {}

        for key, payload in pred_raw.items():
            pair_vec_H[key] = payload["vectors"]
            pair_edges_dict[key] = payload["edges"]

            for idx, edge_5d in enumerate(payload["edges"].t()):
                sx, sy, sz, i, j = edge_5d.tolist()
                lookup_dict[(int(sx), int(sy), int(sz), int(i), int(j))] = (key, idx)

        pred_H_irreps = IrrepsBlockData(
            atoms=tuple(atoms_list),
            atom_counts=Counter(atoms_list),
            pair_vectors=pair_vec_H,
            pair_edges=pair_edges_dict,
            lookup=lookup_dict,
            orbital_cfg=orbital_cfg,
            basis=target_H_matrix.basis,
        )

        # Convert to blocks
        pred_H_matrix = pred_H_irreps.to_blocks(mapper)

        # Filter for partial training if needed
        filtered_pred = filter_blocks_by_partial_train(
            pred_H_matrix, CONFIG["partial_train"]
        )
        filtered_target = filter_blocks_by_partial_train(
            target_H_matrix, CONFIG["partial_train"]
        )
        filtered_overlap = filter_blocks_by_partial_train(
            overlap_e3nn, CONFIG["partial_train"]
        )

        # Create filtered versions for metrics computation
        # ...existing code...

        pred_filtered_blocks = {}
        target_filtered_blocks = {}
        overlap_filtered_blocks = {}

        for key in target_H_matrix.pair_blocks.keys():
            if key in pred_H_matrix.pair_blocks:
                pred_full, pred_mask = filtered_pred[key]
                targ_full, targ_mask = filtered_target[key]
                ovlp_full, ovlp_mask = filtered_overlap[key]

                min_n = min(pred_full.shape[0], targ_full.shape[0], ovlp_full.shape[0])
                mask = pred_mask[:min_n] & targ_mask[:min_n] & ovlp_mask[:min_n]

                if mask.any():
                    pred_filtered_blocks[key] = pred_full[:min_n][mask]
                    target_filtered_blocks[key] = targ_full[:min_n][mask]
                    overlap_filtered_blocks[key] = ovlp_full[:min_n][mask]

        # Create temporary BlockMatrix objects for metrics computation
        pred_filtered = BlockMatrix(
            atoms=target_H_matrix.atoms,
            atom_counts=target_H_matrix.atom_counts,
            pair_blocks=pred_filtered_blocks,
            pair_edges={
                key: target_H_matrix.pair_edges[key]
                for key in pred_filtered_blocks.keys()
            },
            lookup=target_H_matrix.lookup,
            orbital_cfg=target_H_matrix.orbital_cfg,
            basis=target_H_matrix.basis,
        )
        target_filtered = BlockMatrix(
            atoms=target_H_matrix.atoms,
            atom_counts=target_H_matrix.atom_counts,
            pair_blocks=target_filtered_blocks,
            pair_edges={
                key: target_H_matrix.pair_edges[key]
                for key in target_filtered_blocks.keys()
            },
            lookup=target_H_matrix.lookup,
            orbital_cfg=target_H_matrix.orbital_cfg,
            basis=target_H_matrix.basis,
        )
        overlap_filtered = BlockMatrix(
            atoms=overlap_e3nn.atoms,
            atom_counts=overlap_e3nn.atom_counts,
            pair_blocks=overlap_filtered_blocks,
            pair_edges={
                key: overlap_e3nn.pair_edges[key]
                for key in overlap_filtered_blocks.keys()
            },
            lookup=overlap_e3nn.lookup,
            orbital_cfg=overlap_e3nn.orbital_cfg,
            basis=overlap_e3nn.basis,
        )

        # Compute detailed metrics for final evaluation
        final_detailed_metrics = compute_detailed_metrics(
            pred_filtered, target_filtered, overlap_filtered
        )

        print("\n[FINAL PREDICTIONS - Hamiltonian]")
        print(f"\n  Overall Metrics:")
        print(f"    MAE H:                {final_detailed_metrics['mae']:.6e}")
        print(f"    MSE H:                {final_detailed_metrics['mse']:.6e}")
        print(f"    MAE H (modified):     {final_detailed_metrics['mae_mod']:.6e}")
        print(f"    MSE H (modified):     {final_detailed_metrics['mse_mod']:.6e}")
        print(f"    mu_H:                 {final_detailed_metrics['mu_H']:.6e}")
        print(
            f"    Correction MAE:       {final_detailed_metrics['correction_mae']:.6e}"
        )
        print(
            f"    Correction MSE:       {final_detailed_metrics['correction_mse']:.6e}"
        )

        final_metrics = {
            "final/mae_H": final_detailed_metrics["mae"],
            "final/mse_H": final_detailed_metrics["mse"],
            "final/mae_H_mod": final_detailed_metrics["mae_mod"],
            "final/mse_H_mod": final_detailed_metrics["mse_mod"],
            "final/mu_H": final_detailed_metrics["mu_H"],
            "final/correction_mae": final_detailed_metrics["correction_mae"],
            "final/correction_mse": final_detailed_metrics["correction_mse"],
        }

        print("\n  Per-block Metrics:")
        for key in pred_filtered_blocks.keys():
            pred_block = pred_filtered_blocks[key]
            true_block = target_filtered_blocks[key]

            block_mse = F.mse_loss(pred_block, true_block).item()
            block_mae = torch.mean(torch.abs(pred_block - true_block)).item()

            pair_irreps = mapper.get_pair_irreps(key)

            # Get mask info for reporting
            _, mask = filtered_pred[key]
            num_selected = (
                mask[: pred_H_matrix.pair_blocks[key].shape[0]].sum().item()
                if key in pred_H_matrix.pair_blocks
                else 0
            )
            num_total = (
                pred_H_matrix.pair_blocks[key].shape[0]
                if key in pred_H_matrix.pair_blocks
                else 0
            )

            print(f"\n  {key}:")
            print(f"    Block shape: {pred_block.shape}, Irreps: {pair_irreps}")
            if CONFIG["partial_train"] is not None:
                print(
                    f"    Selected blocks: {num_selected}/{num_total} ({CONFIG['partial_train']})"
                )
            print(f"    MSE: {block_mse:.6e}")
            print(f"    MAE: {block_mae:.6e}")
            print(
                f"    Relative error: {block_mae / (torch.abs(true_block).mean().item() + 1e-10):.6%}"
            )

            final_metrics[f"final/{key}_mse"] = block_mse
            final_metrics[f"final/{key}_mae"] = block_mae

        # If irrep decomposition was used, compute and log final per-irrep absolute and relative errors
        if CONFIG["train_on_irrep_parts"] and target_H_irreps is not None:
            final_partial_abs = {}
            final_partial_rel = {}
            _REL_EPS = 1e-12
            for irrep in all_irreps:
                # Filter both prediction and target by this irrep
                pred_irrep_filtered = filter_irreps_block_data_by_irrep(
                    pred_H_irreps, irrep
                )
                target_irrep_filtered = filter_irreps_block_data_by_irrep(
                    target_H_irreps, irrep
                )

                pred_irrep_blocks = pred_irrep_filtered.to_blocks(mapper)
                target_irrep_blocks = target_irrep_filtered.to_blocks(mapper)

                block_rel_errors = []
                block_abs_errors = []
                block_counts = []

                for key in target_irrep_blocks.pair_blocks.keys():
                    if key in pred_irrep_blocks.pair_blocks:
                        pred_blocks = pred_irrep_blocks.pair_blocks[key]
                        targ_blocks_full = target_irrep_blocks.pair_blocks[key]
                        min_n = min(pred_blocks.shape[0], targ_blocks_full.shape[0])
                        if min_n <= 0:
                            continue
                        pred_sel = pred_blocks[:min_n]
                        targ_sel = targ_blocks_full[:min_n]
                        diff = pred_sel - targ_sel
                        abs_error = torch.mean(torch.abs(diff)).item()
                        targ_abs = torch.mean(torch.abs(targ_sel)).item()
                        rel_error = abs_error / (targ_abs + _REL_EPS)
                        block_rel_errors.append(rel_error)
                        block_abs_errors.append(abs_error)
                        block_counts.append(pred_sel.numel())

                irrep_str = str(irrep)
                # Average over blocks
                mean_abs = (
                    sum(block_abs_errors) / len(block_abs_errors)
                    if block_abs_errors
                    else 0.0
                )
                rel = (
                    sum(block_rel_errors) / len(block_rel_errors)
                    if block_rel_errors
                    else 0.0
                )
                final_partial_abs[irrep_str] = mean_abs
                final_partial_rel[irrep_str] = rel

            # Merge into final_metrics for WandB
            for ir, v in final_partial_abs.items():
                final_metrics[f"partial_abs/{ir}"] = v
            for ir, v in final_partial_rel.items():
                final_metrics[f"partial_rel/{ir}"] = v

        # Log final metrics to WandB
        wandb.log(final_metrics)

    # Save final model
    final_model_path = run_checkpoint_dir / "final_model.pt"
    torch.save(
        {
            "epoch": epoch,
            "model_state_dict": network.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "loss": history["loss"][-1],
            "mae_H": history["mae_H"][-1],
            "config": CONFIG,
            "history": history,
            "final_metrics": final_detailed_metrics,
        },
        final_model_path,
    )

    print("\n" + "=" * 80)
    print("STUDY COMPLETE")
    print("=" * 80)
    print(f"\nRun name: {run_name}")
    print(f"Total training epochs: {epoch + 1}")
    print(f"Final loss: {history['loss'][-1]:.6e}")
    print(f"Best loss: {min(history['loss']):.6e} (epoch {best_epoch + 1})")
    print(f"\nCheckpoints saved to: {run_checkpoint_dir}")
    print(f"  Best model: {run_checkpoint_dir / 'best_model.pt'}")
    print(f"  Final model: {final_model_path}")
    print("\n✓ Minimal overfit study finished successfully!")

    # Compile frames to video and log to WandB
    print(f"\n{'='*80}")
    print("VIDEO GENERATION")
    print(f"{'='*80}")
    try:
        video_path = run_checkpoint_dir / "training_progress.mp4"
        if (frame_output_dir).glob("frame_epoch_*.png"):
            compile_frames_to_video(
                frame_output_dir,
                video_path,
                fps=5,
                pattern="frame_epoch_*.png",
            )
            # Log video to WandB
            wandb.log({"training_video": wandb.Video(str(video_path), fps=5)})
            print(f"✓ Training video logged to WandB")
        else:
            print(f"⚠️  No frames found for video generation")
    except Exception as e:
        print(f"⚠️  Warning: Could not generate video: {e}")

    # Finish WandB run
    wandb.finish()
